### ISSUE TITLE
Interrupt signals not working in shell environment.

### ISSUE THREAD

**Issue by rein** [u03bb/mandarinit#2]
Expected behavior: ^C exits running program in session started by mandarinit.
What happens: Nothing.

**Comment by l-a-i-n** [comment]
I think this is being caused by actOnChildProcess not operating on the forked process. Pending further investigation.

I have tested with suckless' sinit (which mandarinit is somewhat based on) and all signals are working in the shell, but with mandarinit, this is not so.

**Comment by l-a-i-n** [comment]
actOnChildProcess needs changing to run inside the call to forkProcess, sequentially after executeFile, and aOCP should retrieve the current PID itself rather than work with what forkProcess returns.

**Comment by rein** [comment]
Okay the bottom line of what was happening here is as follows:

First the signal unblocking was occuring in the parent, then it wasn't occuring in the child due to conditionally checking the PID for 0 like C's fork() works.

I amended that, still wasn't working, because I forgot to execute the signal unblocking BEFORE the execv* call! Oops!

Fixed now and working.
